apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: synergychat-api
  name: synergychat-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: synergychat-api
  template:
    metadata:
      labels:
        app: synergychat-api
    spec:
      volumes:
      - name: synergychat-api-volume
        persistentVolumeClaim:
          claimName: synergychat-api-pvc
      containers:
      - image: docker.io/bootdotdev/synergychat-api:latest
        name: synergychat-api
        envFrom:
        - configMapRef:
            name: synergychat-api-configmap
        volumeMounts:
        - name: synergychat-api-volume
          mountPath: /persist